library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("SPAM Email Classifiers"),
  sidebarPanel(style = "overflow-y:scroll; max-height: 500px; position:relative;",
    h3('Choose the desired classifiers'),
    checkboxGroupInput("id2", 
                        "All columns in the SPAM dataset:",
                        c("make"="make",
                            "address"="address",
                            "all"="all",
                            "num3d"="num3d",
                            "our"="our",
                            "over"="over",
                            "remove"="remove",
                            "internet"="internet",
                            "order"="order",
                            "mail"="mail",
                            "receive"="receive",
                            "will"="will",
                            "people"="people",
                            "report"="report",
                            "addresses"="addresses",
                            "free"="free",
                            "business"="business",
                            "email"="email",
                            "you"="you",
                            "credit"="credit",
                            "your"="your",
                            "font"="font",
                            "num000"="num000",
                            "money"="money",
                            "hp"="hp",
                            "hpl"="hpl",
                            "george"="george",
                            "num650"="num650",
                            "lab"="lab",
                            "labs","labs",
                            "telnet"="telnet",
                            "num857"="num857",
                            "data"="data",
                            "num415"="num415",
                            "num85"="num85",
                            "technology"="technology",
                            "num1999"="num1999",
                            "parts"="parts",
                            "pm"="pm",
                            "direct"="direct",
                            "cs"="cs",
                            "meeting" ="meeting" ,
                            "original"="original",
                            "project"="project",
                            "re"="re",
                            "edu"="edu",
                            "table"="table",
                            "conference"="conference",
                            "charSemicolon"="charSemicolon",
                            "charRoundbracket"="charRoundbracket",
                            "charSquarebracket"="charSquarebracket",
                            "charExclamation"="charExclamation",
                            "charDollar"="charDollar",
                            "charHash"="charHash",
                            "capitalAve"="capitalAve",
                            "capitalLong"="capitalLong",
                            "capitalTotal"="capitalTotal"
                     ), selected=c("make", "address", "all", "num3d", "our", "over", "remove", "internet", "order", "mail", "receive", "will", "people", "report", "addresses", "free", "business", "email", "you", "credit", "your", "font", "num000", "money", "hp", "hpl", "george", "num650", "lab", "labs", "telnet", "num857", "data", "num415", "num85", "technology", "num1999", "parts", "pm", "direct", "cs", "meeting", "original", "project", "re", "edu", "table", "conference", "charSemicolon", "charRoundbracket", "charSquarebracket", "charExclamation", "charDollar", "charHash", "capitalAve", "capitalLong", "capitalTotal"))
  ),
  mainPanel(
      h3('Result'),
      h4('Running may take up to 20 seconds...'),
      verbatimTextOutput("oid1"),
      HTML("<br><br>"),
      h3('How it works?'),
      p('Dataset spam in library <kernlab> has 4601 rows and 58 columns.'),
      p('We split the dataset into 75% for training and 25% for testing, using random sampling (createDataPartition() in library <caret>).'),
      code('inTrain <- createDataPartition(y=spam$type, p=0.75, list=FALSE)'),
      HTML("<br>"),
      code('training <- spam[inTrain,]'),
      HTML("<br>"),
      code('testing <- spam[-inTrain,]'),
      p('Then, the chosen columns besides together with the <type> (spam, nonspam) will be used to train a model using Generalized Linear Models (train() in library <caret>).'),
      code('modelFit <- train(type ~., data=trainingTemp, method="glm")'),
      p('Using the built model, make prediction.'),
      code('predictions <- predict(modelFit, newdata=testingTemp)'),
      p('Finally, compare the predicted values with the real ones.'),
      code('confusionMatrix(predictions,testingTemp$type)')
  )
))

