library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("SPAM Email Classifiers"),
  
  sidebarPanel(style = "overflow-y:scroll; max-height: 500px; position:relative;",
    h3('Choose the desired classifiers'),
    checkboxGroupInput("id2", 
                        "All columns in the SPAM dataset:",
                        c("make"="make",
                            "address"="address",
                            "all"="all",
                            "num3d"="num3d",
                            "our"="our",
                            "over"="over",
                            "remove"="remove",
                            "internet"="internet",
                            "order"="order",
                            "mail"="mail",
                            "receive"="receive",
                            "will"="will",
                            "people"="people",
                            "report"="report",
                            "addresses"="addresses",
                            "free"="free",
                            "business"="business",
                            "email"="email",
                            "you"="you",
                            "credit"="credit",
                            "your"="your",
                            "font"="font",
                            "num000"="num000",
                            "money"="money",
                            "hp"="hp",
                            "hpl"="hpl",
                            "george"="george",
                            "num650"="num650",
                            "lab"="lab",
                            "labs","labs",
                            "telnet"="telnet",
                            "num857"="num857",
                            "data"="data",
                            "num415"="num415",
                            "num85"="num85",
                            "technology"="technology",
                            "num1999"="num1999",
                            "parts"="parts",
                            "pm"="pm",
                            "direct"="direct",
                            "cs"="cs",
                            "meeting" ="meeting" ,
                            "original"="original",
                            "project"="project",
                            "re"="re",
                            "edu"="edu",
                            "table"="table",
                            "conference"="conference",
                            "charSemicolon"="charSemicolon",
                            "charRoundbracket"="charRoundbracket",
                            "charSquarebracket"="charSquarebracket",
                            "charExclamation"="charExclamation",
                            "charDollar"="charDollar",
                            "charHash"="charHash",
                            "capitalAve"="capitalAve",
                            "capitalLong"="capitalLong",
                            "capitalTotal"="capitalTotal"
                     ), selected=c("make", "address", "all", "num3d", "our", "over", "remove", "internet", "order", "mail", "receive", "will", "people", "report", "addresses", "free", "business", "email", "you", "credit", "your", "font", "num000", "money", "hp", "hpl", "george", "num650", "lab", "labs", "telnet", "num857", "data", "num415", "num85", "technology", "num1999", "parts", "pm", "direct", "cs", "meeting", "original", "project", "re", "edu", "table", "conference", "charSemicolon", "charRoundbracket", "charSquarebracket", "charExclamation", "charDollar", "charHash", "capitalAve", "capitalLong", "capitalTotal"))
  ),
  mainPanel(
      a("Source code here!",     href="https://github.com/ThachNgocTran/DevelopingDataProductsProject/tree/master/ShinyAppCode", target="_blank"),
      h3('Result'),
      h4('Running may take up to 30 seconds. Please be patient...'),
      verbatimTextOutput("oid1"),
      h3('How it works?'),
      p('An email may have many properties such as "address", "contain dollar sign or not", etc. These properties are useful in training a model that helps classify an email (spam or non-spam).'),
      p('Besides are 57 properties in the dataset "spam" in library "kernlab". Choose the ones to train a model and see the results.'),
      p('Note: The GUI is highly reactive: one change in chosen properties makes results immediately!'),
      a("Dataset Description",     href="https://archive.ics.uci.edu/ml/datasets/Spambase", target="_blank"),
      h3('Technical Details:'),
      p('Predictive Algorithm: Generalized Linear Models.'),
      p('Training Set: 75%, Testing Set: 25%. Use Random Sampling to split.')
  )
))

